export const courses = [
    {
        id: "1",
        title: "Internet & Computing Core Certification (IC3)",
        image: "/IC3.webp",
        description: "Gain foundational computing skills, including internet usage and core applications.",
        duration: "2 months",
        level: "Beginner",
        price: 5500,
        curriculum: [
            "Introduction to Computing",
            "Internet and Email Basics",
            "Office Productivity Tools",
            "Digital Communication",
            "Computer Security Basics",
        ],
    },
    {
        id: "2",
        title: "Advanced Certificate in Computer Applications (ACCA)",
        image: "/computerapplications.png",
        description: "Enhance your computer proficiency with advanced application skills.",
        duration: "3 months",
        level: "Intermediate",
        price: 7500,
        curriculum: [
            "Advanced Microsoft Office",
            "Data Management",
            "Presentation Tools",
            "Internet Research & Productivity",
            "Basic Troubleshooting",
        ],
    },
    {
        id: "3",
        title: "Web Designing",
        image: "/web-design-inspiration.jpg",
        description: "Learn how to design and develop modern, responsive websites.",
        duration: "2 months",
        level: "Intermediate",
        price: 10000,
        curriculum: [
            "HTML & CSS Fundamentals",
            "JavaScript Basics",
            "Responsive Design",
            "Web Graphics",
            "Website Hosting & Deployment",
        ],
    },
    {
        id: "4",
        title: "Computerized Accounting (QuickBooks/Sage)",
        image: "/computerized-accounting.jpeg",
        description: "Master accounting software like QuickBooks and Sage for business finance management.",
        duration: "2.5 months",
        level: "Intermediate",
        price: 7500,
        curriculum: [
            "Introduction to Accounting Software",
            "Financial Data Entry",
            "Generating Reports",
            "Payroll Management",
            "Taxation Basics",
        ],
    },
    {
        id: "5",
        title: "Computer Technician",
        image: "/pc-support-technician.jpg",
        description: "Learn hardware and software troubleshooting to become a computer technician.",
        duration: "1 month",
        level: "Beginner",
        price: 5000,
        curriculum: [
            "Computer Hardware Basics",
            "Operating System Installation",
            "Troubleshooting Techniques",
            "Network Basics",
            "Data Backup & Recovery",
        ],
    },
    {
        id: "6",
        title: "JavaScript Programming",
        image: "/javascript.webp",
        description: "Learn JavaScript programming for web development.",
        duration: "1 month",
        level: "Beginner",
        price: 3500,
        curriculum: [
            "JavaScript Basics",
            "DOM Manipulation",
            "Event Handling",
            "Basic Algorithms",
            "Intro to ES6",
        ],
    },
    {
        id: "7",
        title: "Visual Basic Programming",
        image: "/visual-basic.jpg",
        description: "Develop applications using Visual Basic.",
        duration: "1 month",
        level: "Beginner",
        price: 3500,
        curriculum: [
            "Visual Basic Basics",
            "Form Controls",
            "Event-Driven Programming",
            "Database Connectivity",
            "Error Handling",
        ],
    },
    {
        id: "8",
        title: "Fox Pro Programming",
        image: "/fox-pro.png",
        description: "Learn database programming with Fox Pro.",
        duration: "1 month",
        level: "Beginner",
        price: 3500,
        curriculum: [
            "Fox Pro Basics",
            "Database Management",
            "SQL Queries",
            "Report Generation",
            "Application Development",
        ],
    },
    {
        id: "9",
        title: "C++ Programming",
        image: "/ISO_C++_Logo.svg.png",
        description: "Learn object-oriented programming with C++.",
        duration: "3 months",
        level: "Intermediate",
        price: 15000,
        curriculum: [
            "C++ Basics",
            "Object-Oriented Programming",
            "Data Structures",
            "File Handling",
            "Advanced Algorithms",
        ],
    },
    {
        id: "10",
        title: "MySQL Programming",
        image: "/mysql.png",
        description: "Learn database management with MySQL.",
        duration: "3 months",
        level: "Intermediate",
        price: 12000,
        curriculum: [
            "MySQL Basics",
            "Database Normalization",
            "SQL Queries & Joins",
            "Stored Procedures",
            "Database Security",
        ],
    },
  ];